
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: adminpass  # Replace with your MySQL password
      MYSQL_DATABASE: ofs_database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: adminpass
      DB_NAME: ofs_database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    volumes:
      - ./client:/app

volumes:
  db_data: